### ISSUE TITLE
Incorrect minimum Python version specified + other minor issues

### ISSUE THREAD

**Issue by kguzek** [BUZZARDGTA/GTA-V-Session-Sniffer#10] opened 2024-11-30 20:34 UTC
The program checks if the user's Python installation is at least 3.9, and exits prematurely if not. However, the script uses features from versions 3.12+, such as reusing the same quotes in f-strings:
```python
219 | return f"v{self.major}.{self.minor}.{self.patch} - {self.date}{f" ({self.time})" if self.time else ""}"
```
or using backslashes (e.g. with `\n` or `\"` sequences) in f-strings:
```python
1213 | \"{USERIP_DATABASES_PATH}\\{initial_userip_entry.database_name}.ini\":
```

These changes are documented in the following python.org changelog:
https://docs.python.org/3.12/whatsnew/3.12.html#pep-701-syntactic-formalization-of-f-strings

When running the script in a Python version that is >= 3.9 but < 3.12, it raises several `SyntaxError`s.
Suggested fix: bump the minimum version requirement on line `61` to major 3 minor 12, as well as the related print statements.

----

Additionally, most Python linters dictate that the import order of modules should be as follows:
1. Standard libraries
2. Third-party libraries
3. Local libraries

Implementing this would simply involve rearranging the import sections, as they have already been grouped up.

And ending on a general remark, wow dude! This script should really be split up into more modules. And I mean a *lot* more modules, since a 4000+ line Python file is crazy. That's a quite conservative quote, too, since the code's been compressed, and my linter automatically formats it into around 5500 lines. 

The program flow would be a lot more straightforward and easy to maintain with smaller files, and even the time to save the file and run linters would be drastically reduced. But that's just the aside, the main topic of this issue is the incorrect versioning.

**Comment by BUZZARDGTA** [comment] 2024-11-30 20:43
Hello, thanks a lot for the remarks. I will probably adjust the version number you can also make a pull request for it.

Concerning splitting up the code into more modules, I'm more and more looking for it. Now the script is pretty much in a finished state. All left to do is optimization. There's literally no new features to add at least not that I'm aware about and the program is perfect, so yeah again there's only room for optimization now.

For a dumb example, function (Thread) `stdout_render_core` still has in memory the "launcher" variable `error_updating__flag` this is one of probably Tens or even Thousands of examples. I think we could not only improves readability but also memory management as if these are loaded into modules, then the memory from `stdout_render_core` (which is the main loop of the script running forever) could execute slightly faster. Of course it's just code optimization and most people would think I'm a nerd but, I'm looking more and more into modularizing the script. It's planned :)

Thanks for your review, it's nice seeing people around my script, I've put a lot of efforts on this project. So having people helping me with the open source makes me soOoOo happy

**Comment by kguzek** [comment] 2024-11-30 20:54
Alright that's good to hear, it's definitely a step in the right direction if you're already looking into modularising it, as well as improving memory management.

I'm working on a PR now with a few additional fixes (missing annotations, potential edge cases).

**Comment by BUZZARDGTA** [comment] 2024-11-30 21:55
Ah I just come back on PC didn't read the PR yet, hum about `Wireshark v4.2.8` forced, yes it's intentional.
Wireshark is not on GitHub, it's open source on another platform and I didn't bother creating an acc there ONLY for opening in issue they introduced on newer version. So I decided to lock on the stable version.
I should have said eearlier but the problem is that people "rejoining" would not shows up or something like that. tshark would simply skip all packets from IPs idle and coming back. Somehow lol. It might have been fixed now, I will look at it one day, maybe blacklist THIS or THESE broken versions of TSHARK instead of forcing the actual version.

**Comment by BUZZARDGTA** [comment] 2024-11-30 21:57
But overall I think forcing is a great solution as everyone have the same program running. So technically one guy cannot have an issue that me or someone else do not have. If one person have an issue then everyone has the same and we can easily find a solution for it. Makes things easier honestly.

**Comment by BUZZARDGTA** [comment] 2024-11-30 21:59
Another thing btw is someone asked me to add in settings the ability to hide `First Seen  │ Last Rejoin │ Last Seen ↓ │ Usernames        │ Rejoins │ T. Packets │ Packets` these fields, but yeah no, okay maybe they specfically dont need it but it's the essence of what makes my program interesting compared to other sniffers, it's my advertisement and I do think everyone needs them, they're essential to me everydays. I don't want to add the possibility to hide those.

**Comment by kguzek** [comment] 2024-11-30 22:04
> Ah I just come back on PC didn't read the PR yet, hum about `Wireshark v4.2.8` forced, yes it's intentional. Wireshark is not on GitHub, it's open source on another platform and I didn't bother creating an acc there ONLY for opening in issue they introduced on newer version. So I decided to lock on the stable version. I should have said eearlier but the problem is that people "rejoining" would not shows up or something like that. tshark would simply skip all packets from IPs idle and coming back. Somehow lol. It might have been fixed now, I will look at it one day, maybe blacklist THIS or THESE broken versions of TSHARK instead of forcing the actual version.

Ah okay I see, now that I think about it my `Rejoins` field has all been zeros.

**Comment by BUZZARDGTA** [comment] 2024-11-30 22:05
I think the bug was it goes increase to 1, they are connected and then instantly gets down to disconnected even tho they are still in your session playing w you.

**Comment by kguzek** [comment] 2024-11-30 22:06
> Another thing btw is someone asked me to add in settings the ability to hide `First Seen │ Last Rejoin │ Last Seen ↓ │ Usernames │ Rejoins │ T. Packets │ Packets` these fields, but yeah no, okay maybe they specfically dont need it but it's the essence of what makes my program interesting compared to other sniffers, it's my advertisement and I do think everyone needs them, they're essential to me everydays. I don't want and wont add in the future the possibility to hide those.

To be honest those are quite basic fields, I don't see the need to be able to hide them. But that's the beauty of open source - if someone desparately needs that feature they can create their own fork and add it in, especially since it's quite a trivial thing to implement.

**Comment by BUZZARDGTA** [comment] 2024-11-30 22:07
Yeah it's very easy to hide, just follow how I hide others hideable fiels and that's it

**Closed** 2024-11-30 22:42 UTC
